version: "3"
services:
  ahem:
    image: o4oren/ahem:latest
    build:
      context: .
    ports:
      - "3000:3000"
      - "25:2525"
    tty: true
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      - serverBaseUri=http://localhost:3000
      - mongoConnectUrl=mongodb://mongodb:27017/
      - appListenPort=3000
      - smtpPort=2525
      - allowAutocomplete=true
      - allowedDomains=my.domain.com
      - jwtSecret=AH3M 709 S3cR3T
      - emailDeleteInterval=5
      - emailDeleteAge=10
    volumes:
      - ./:/app


  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net1
networks:
  net1: